Makao: LobbyWidget Class Reference
LobbyWidget Class Reference
#include <lobbywidget.h>
Public Member Functions
~LobbyWidget ()
void startServer ()
void startClient ()
Static Public Member Functions
static LobbyWidget * createServerLobby (QWidget *parent, Server *server, int port)
static LobbyWidget * createClientLobby (QWidget *parent, Client *client, QString serverIP, int port)
Constructor & Destructor Documentation
LobbyWidget::~LobbyWidget ()
Member Function Documentation
LobbyWidget * LobbyWidget::createClientLobby (QWidget * parent, Client * client, QString serverIP, int port) static
LobbyWidget * LobbyWidget::createServerLobby (QWidget * parent, Server * server, int port) static
void LobbyWidget::startClient ()
References GameScreenWidget::GameScreenWidget(), Player::getName(), MessageType::PlayerConnected, MessageType::PlayerDisconnected, MessageType::PlayerSetNewName, MessageType::SetName, Utils::showNotBlockingMessageBox(), and MessageType::StartGame.
void LobbyWidget::startServer ()
References Utils::showNotBlockingMessageBox().
The documentation for this class was generated from the following files:
D:/makao/src/lobbywidget.h
D:/makao/src/lobbywidget.cpp