Makao: Client Class Reference
Client Class Reference
#include <client.h>
Signals
void onConnected ()
void onDisconnected ()
void onError (QAbstractSocket::SocketError socketError)
void onDataReceived (int messageType, QString message)
Public Member Functions
Client (QObject *parent, Player *player)
~Client ()
void connectToHost (QString ip, quint16 port)
bool isConnected ()
void sendMessage (int messageType, QString message)
void disconnectFromHost ()
const QTcpSocket * getSocket () const
Player * getPlayer () const
QList< Player * > getOtherPlayers ()
Constructor & Destructor Documentation
Client::Client (QObject * parent, Player * player)
Client::~Client ()
References disconnectFromHost().
Member Function Documentation
void Client::connectToHost (QString ip, quint16 port)
void Client::disconnectFromHost ()
QList<Player*> Client::getOtherPlayers () inline
References onConnected(), onDataReceived(), onDisconnected(), and onError().
Player* Client::getPlayer () const inline
const QTcpSocket* Client::getSocket () const inline
bool Client::isConnected ()
void Client::onConnected () signal
void Client::onDataReceived (int messageType, QString message) signal
void Client::onDisconnected () signal
void Client::onError (QAbstractSocket::SocketError socketError) signal
void Client::sendMessage (int messageType, QString message)
References onConnected(), onDataReceived(), onDisconnected(), onError(), MessageType::PlayerConnected, MessageType::PlayerDisconnected, MessageType::PlayerSetNewName, MessageType::SetName, and MessageType::WelcomeClientSetId.
The documentation for this class was generated from the following files:
D:/makao/src/client.h
D:/makao/src/client.cpp