Makao: Server Class Reference
Server Class Reference
#include <server.h>
Signals
void onConnected (Player const *const player)
void onDisconnected (Player const *const player)
void afterDisconnected ()
void onError (QAbstractSocket::SocketError socketError)
void onDataReceived (Player *sender, int messageType, QString message)
Public Member Functions
Server (QObject *parent, Player *hostPlayer)
~Server ()
Player * getHostPlayer () const
QList< Player * > getOtherPlayers ()
void sendMessage (Player const *const player, int messageType, QString message)
void sendMessage (QTcpSocket *socket, int messageType, QString message)
void sendMessageToAllPlayers (int messageType, QString message)
void shutdown ()
Public Attributes
bool allowConnecting
Protected Member Functions
void incomingConnection (qintptr socketDescriptor) Q_DECL_OVERRIDE
Constructor & Destructor Documentation
Server::Server (QObject * parent, Player * hostPlayer)
Server::~Server ()
References shutdown().
Member Function Documentation
void Server::afterDisconnected () signal
Player* Server::getHostPlayer () const inline
QList<Player*> Server::getOtherPlayers () inline
References afterDisconnected(), incomingConnection(), onConnected(), onDataReceived(), onDisconnected(), onError(), sendMessage(), sendMessageToAllPlayers(), and shutdown().
void Server::incomingConnection (qintptr socketDescriptor) protected
References allowConnecting, onConnected(), MessageType::PlayerConnected, sendMessage(), sendMessageToAllPlayers(), and MessageType::WelcomeClientSetId.
void Server::onConnected (Player const *const player) signal
void Server::onDataReceived (Player * sender, int messageType, QString message) signal
void Server::onDisconnected (Player const *const player) signal
void Server::onError (QAbstractSocket::SocketError socketError) signal
void Server::sendMessage (Player const *const player, int messageType, QString message)
void Server::sendMessage (QTcpSocket * socket, int messageType, QString message)
void Server::sendMessageToAllPlayers (int messageType, QString message)
References afterDisconnected(), onDataReceived(), onDisconnected(), onError(), MessageType::PlayerConnected, MessageType::PlayerDisconnected, MessageType::PlayerSetNewName, sendMessage(), and MessageType::SetName.
void Server::shutdown ()
Member Data Documentation
bool Server::allowConnecting
The documentation for this class was generated from the following files:
D:/makao/src/server.h
D:/makao/src/server.cpp