Makao: GameScreenWidget Class Reference
GameScreenWidget Class Reference
#include <gamescreenwidget.h>
Public Member Functions
GameScreenWidget (QWidget *parent, Server *server, Client *client, bool isServer)
~GameScreenWidget ()
Constructor & Destructor Documentation
GameScreenWidget::GameScreenWidget (QWidget * parent, Server * server, Client * client, bool isServer) explicit
References Server::getHostPlayer(), Player::getName(), Server::getOtherPlayers(), Client::getOtherPlayers(), Client::getPlayer(), MessageType::Ready, Client::sendMessage(), Table::topCard(), and OpponentCardsWidget::Vertical.
GameScreenWidget::~GameScreenWidget ()
References MessageType::AddCard, Player::addCard(), Table::CanPlayCard(), MessageType::CantPlayCard, Card::Card10, Card::Card4, Card::Card5, Card::Card6, Card::Card7, Card::Card8, Card::Card9, Player::cardAt(), Player::cardsCount, MessageType::CardsNumber, Card::deserialize(), Player::getId(), Table::getIsWar(), Player::getName(), Table::getNewCard(), Card::getPip(), Card::getPipAsText(), Card::getSuit(), Card::getSuitAsText(), Table::getWarCardsCount(), Card::Jack, Card::King, Table::PlayCard(), MessageType::PlayCard, MessageType::PlayerTurn, MessageType::Ready, Player::ready, MessageType::RemoveCard, Player::removeCard(), Table::reset4Flag(), MessageType::ResetTurnWaitCounter, Table::resetWarFlag(), Card::serialize(), OpponentCardsWidget::setCardsNumber(), Table::setJackRequestedPip(), MessageType::SetTableCard, Utils::showJackSelectionMessageBox(), Utils::showNotBlockingMessageBox(), Card::Spade, MessageType::TakeNewCard, Table::topCard(), and Player::waitingTurns.
The documentation for this class was generated from the following files:
D:/makao/src/gamescreenwidget.h
D:/makao/src/gamescreenwidget.cpp