Makao: CardsWidget Class Reference
CardsWidget Class Reference
#include <cardswidget.h>
Signals
void cardClicked (const Card &card, int cardIndex)
Public Member Functions
CardsWidget (QWidget *parent=nullptr)
~CardsWidget ()
void addCard (const Card &card)
void removeCard (int index)
void rearrangeCards ()
Static Public Member Functions
static int calculateCardHorizontalPosition (int cardIndex)
Constructor & Destructor Documentation
CardsWidget::CardsWidget (QWidget * parent = nullptr) explicit
CardsWidget::~CardsWidget ()
Member Function Documentation
void CardsWidget::addCard (const Card & card)
References calculateCardHorizontalPosition(), cardClicked(), and SingleCardWidget::cardClicked().
int CardsWidget::calculateCardHorizontalPosition (int cardIndex) static
void CardsWidget::cardClicked (const Card & card, int cardIndex) signal
void CardsWidget::rearrangeCards ()
References calculateCardHorizontalPosition().
void CardsWidget::removeCard (int index)
References rearrangeCards().
The documentation for this class was generated from the following files:
D:/makao/src/cardswidget.h
D:/makao/src/cardswidget.cpp