Makao: SingleCardWidget Class Reference
SingleCardWidget Class Reference
#include <singlecardwidget.h>
Signals
void cardClicked (const Card &card, const SingleCardWidget *widget)
Public Member Functions
SingleCardWidget (const Card &card, QWidget *parent=0)
~SingleCardWidget ()
Card getCard () const
Constructor & Destructor Documentation
SingleCardWidget::SingleCardWidget (const Card & card, QWidget * parent = 0) explicit
References Card::getColor(), Card::getPipAsText(), Card::getSuitAsText(), and Card::Red.
SingleCardWidget::~SingleCardWidget ()
Member Function Documentation
void SingleCardWidget::cardClicked (const Card & card, const SingleCardWidget * widget) signal
Card SingleCardWidget::getCard () const
References cardClicked().
The documentation for this class was generated from the following files:
D:/makao/src/singlecardwidget.h
D:/makao/src/singlecardwidget.cpp