Makao: Table Class Reference
Table Class Reference
#include <table.h>
Public Member Functions
Table ()
bool CanPlayCard (const Card &card) const
void PlayCard (const Card &card)
void PlayAce (const Card &aceCard, Card::Suit changedToSuit)
void PlayJack (const Card &jackCard, Card::Pip requestedPip)
Card getNewCard ()
Card topCard ()
void reset4Flag ()
bool getIsWar () const
bool getIsRequest () const
bool getIsRequestFinal () const
int getWarCardsCount () const
void resetWarFlag ()
void setJackRequestedPip (Card::Pip pip)
Constructor & Destructor Documentation
Table::Table ()
References Card::Card10, Card::Card5, and getNewCard().
Member Function Documentation
bool Table::CanPlayCard (const Card & card) const
References Card::Ace, Card::Card2, Card::Card3, Card::Card4, Card::getPip(), Card::getSuit(), Card::Jack, Card::King, and Card::Queen.
bool Table::getIsRequest () const inline
bool Table::getIsRequestFinal () const inline
bool Table::getIsWar () const inline
Card Table::getNewCard ()
References Card::Ace, Card::Card2, Card::Heart, and Card::Spade.
int Table::getWarCardsCount () const inline
void Table::PlayAce (const Card & aceCard, Card::Suit changedToSuit)
References PlayCard().
void Table::PlayCard (const Card & card)
References CanPlayCard(), Card::Card2, Card::Card3, Card::Card4, Card::getPip(), Card::getSuit(), Card::Heart, Card::Jack, Card::King, and Card::Spade.
void Table::PlayJack (const Card & jackCard, Card::Pip requestedPip)
References Card::Ace, Card::getPip(), Card::getSuit(), Card::Jack, and PlayCard().
void Table::reset4Flag ()
void Table::resetWarFlag () inline
void Table::setJackRequestedPip (Card::Pip pip) inline
Card Table::topCard ()
The documentation for this class was generated from the following files:
D:/makao/src/table.h
D:/makao/src/table.cpp