Makao: Card Class Reference
Card Class Reference
#include <card.h>
Public Types
enum Suit { Suit::Heart, Suit::Diamond, Suit::Club, Suit::Spade }
enum Pip {
Pip::Card2, Pip::Card3, Pip::Card4, Pip::Card5,
Pip::Card6, Pip::Card7, Pip::Card8, Pip::Card9,
Pip::Card10, Pip::Jack, Pip::Queen, Pip::King,
Pip::Ace
}
enum Color { Color::Black, Color::Red }
Public Member Functions
Card (const Suit suit, const Pip pip)
Card (const Card &card)
Suit getSuit () const
Pip getPip () const
Color getColor () const
QString getSuitAsText () const
QString getPipAsText () const
int getSuitAsInt () const
int getPipAsInt () const
QString serialize () const
Static Public Member Functions
static Card deserialize (QString str)
Member Enumeration Documentation
enum Card::Color strong
Enumerator
Black
Red
enum Card::Pip strong
Enumerator
Card2
Card3
Card4
Card5
Card6
Card7
Card8
Card9
Card10
Jack
Queen
King
Ace
enum Card::Suit strong
Enumerator
Heart
Diamond
Club
Spade
Constructor & Destructor Documentation
Card::Card (const Suit suit, const Pip pip)
Card::Card (const Card & card)
Member Function Documentation
Card Card::deserialize (QString str) static
References Card().
Card::Color Card::getColor () const
References Black, Diamond, Heart, and Red.
Card::Pip Card::getPip () const
int Card::getPipAsInt () const inline
QString Card::getPipAsText () const
References Ace, Card10, Card2, Card3, Card4, Card5, Card6, Card7, Card8, Card9, Jack, King, and Queen.
Card::Suit Card::getSuit () const
int Card::getSuitAsInt () const inline
QString Card::getSuitAsText () const
References Club, Diamond, Heart, and Spade.
QString Card::serialize () const inline
References deserialize(), getPipAsInt(), and getSuitAsInt().
The documentation for this class was generated from the following files:
D:/makao/src/card.h
D:/makao/src/card.cpp